# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (1, 'Deactive')], default=1)),
                ('gender', models.IntegerField(choices=[(1, 'Men'), (0, 'Woman')], default=1)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
