# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:08
from __future__ import unicode_literals

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=1, help_text='record revision number'),
        ),
    ]
