# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Deactive')], default=1)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=15)),
                ('note', models.CharField(default='', max_length=256)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (1, 'Deactive')], default=1)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=15)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDeposit',
            fields=[
                ('transactionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.TransactionBase')),
            ],
            bases=('payment.transactionbase',),
        ),
        migrations.CreateModel(
            name='TransactionLoanPay',
            fields=[
                ('transactionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.TransactionBase')),
            ],
            bases=('payment.transactionbase',),
        ),
        migrations.CreateModel(
            name='TransactionWithdraw',
            fields=[
                ('transactionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.TransactionBase')),
            ],
            bases=('payment.transactionbase',),
        ),
        migrations.AddField(
            model_name='transactionbase',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='wallet_credit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_credit', to='payment.Wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='wallet_debit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_debit', to='payment.Wallet'),
        ),
        migrations.AddField(
            model_name='transactionloanpay',
            name='loan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Loan'),
        ),
        migrations.AddField(
            model_name='transactiondeposit',
            name='withdraw',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.TransactionWithdraw'),
        ),
        migrations.AddField(
            model_name='loan',
            name='transaction',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.TransactionWithdraw'),
        ),
    ]
